In [1]:
import numpy as np
import sys

In [2]:
a = [1,2,3,4,5]
b = np.array([1,2,3,4,5])

In [3]:
print(a)
print(b)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [4]:
sys.getsizeof(a)

104

In [5]:
b.nbytes

20

In [6]:
# Array 1D

d1 = np.array([1,2,3])
print(d1)

[1 2 3]


In [7]:
d1.shape

(3,)

In [8]:
d1.ndim

1

In [9]:
d1.dtype

dtype('int32')

In [10]:
# Array 2D

# Para fazer 2D, precisa colocar virgula apos os colchetes e colocar todos dentro de outro colchete 
# [ [ 1D ] , [ 2D ] ]

d2 = np.array([[1,2,3],[4,5,6]])
print(d2)

[[1 2 3]
 [4 5 6]]


In [11]:
d2.shape

(2, 3)

In [12]:
d2.ndim

2

In [13]:
d2.dtype

dtype('int32')

In [14]:
# Array 3D

# Para fazer 3D, precisa colocar os 2 elementos da 2D dentro de colchetes. 
# [ [ [ 1D ] , [ 1D ] ] , [ [ 2D ] , [ 2D ] ] ]

d3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
d3.shape

(2, 2, 2)

In [16]:
d3.ndim

3

In [17]:
d3.dtype

dtype('int32')

In [18]:
## Somando duas arrays
import numpy as np

In [19]:
a = [2,3,4]
b = [2,3,4]

In [20]:
result = a + b
result

[2, 3, 4, 2, 3, 4]

In [21]:
a = np.array([2,3,4])
b = np.array([2,3,4])

In [22]:
result = np.add(a,b)
print(result)

[4 6 8]


In [23]:
## Selecionar itens especificos dentro de array

a = np.array([[2,3,4,5], [6,7,8,9]])
print(a)

[[2 3 4 5]
 [6 7 8 9]]


In [24]:
# array = [ Linha , Coluna ] // array=[row,column]
a[1,2] # 8
# a[1,3] # 9
# a[3,1] # 5
# a[1,-1] # 9

8

In [25]:
# somente a linha(row)
# com o : o numpy entende que quer todas os valores da coluna
a[0,:]

array([2, 3, 4, 5])

In [26]:
# somente a coluna(column)
# com o : o numpy entende que quer todas os valores da linha
a[:,1] 

array([3, 7])